#### 常见的Tensor
- 0:scalar
- 1:vector
- 2:matrix
- 3:n-dimensioal tensor

In [1]:
import torch
from torch import tensor

scalar通常是个数值

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

In [6]:
x.item()

42.0

#### vector
- 例如[-5., 2.,0.]在深度学习中通常指特征，例如词向量特征，某一维度特征等

In [9]:
v  = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [10]:
# 查看维度
v.dim()

1

In [11]:
v.size()

torch.Size([3])

#### Matrix 一般计算的都是矩阵，通常都是多维的

In [3]:
m = tensor([[1.,2.], [3., 4.]])
m

tensor([[1., 2.],
        [3., 4.]])

In [4]:
m.dim()

2

In [6]:
m.matmul(m)

tensor([[ 7., 10.],
        [15., 22.]])

In [15]:
tensor([1., 0.]).matmul(m)

tensor([1., 2.])

In [16]:
m * m

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [17]:
tensor([1., 2.]).matmul(m)

tensor([ 7., 10.])