#### dim
- dim就是维数，比如数组会有一维数组，二维数组，numpy的dim维数同理
- 那如何判断numpy的维数,最简单的办法就是数一数“中括号”的数量，没有中括号,dim=0;1个中括号，dim=1;2个中括号,dim=2 ...以此类推
1. a = np.array([[1,2,3],[2,3,4]])在array和第一行元素1,2,3中间有2个[，说明是2维。
2. a = np.array(3)，在array和第一个元素3中间没有[，所以是0维。
3. a = np.array([4])，在array和第一个元素4中间有一个[，说明是1维。

In [1]:
import numpy as np

a = np.array(3)
print(a.ndim)   # a的维度ndim=3

b = np.array([2])
print(b.ndim)  # b的维度ndim=1

c = np.array([[1,2,3],[2,3,4]])
print(c.ndim)  # c的维度ndim=2

0
1
2


#### shape
- shape表示numpy数组是什么形状的，比如一个二维数组是几行几列
##### 备注
- 使用np.array构造一个2维的数组，使用array.shape查看数组的shape形状
- (2, 3)表明numpy数组是2行3列的数组，第一行:1,2,3;第二行:2,3,4

In [2]:
array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array.shape)

(2, 3)


#### size
- size表示数组中一共有多少个元素

In [3]:
array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array.size)

6


In [4]:
import numpy as np

array = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])


print(array)  # 打印矩阵
print('number of dim:', array.ndim)  # dim维度 2
print('shape:', array.shape)  # shape（几行几列）shape(2,3) 代表2行3列
print('size:', array.size)  # size 总共有多少个元素在里面

[[1 2 3]
 [2 3 4]
 [3 4 5]]
number of dim: 2
shape: (3, 3)
size: 9
