## 内容
1. 基本切片和索引
2. 数组索引
3. 布尔数组索引
4. 缺省索引
5. 索引数组与切片结合

### 1、基本切片和索引
基本切片(base slicing)将python的基本概念扩展到N维，当obj是一个切片对象(由方括号内的start:stop:step表示法构造)整数或切片对象和整数的元组时，会产生切片操作
#### 1.1 单元素索引

In [1]:
from IPython.display import Image
import numpy as np

# 一维
x = np.arange(10)
print(x)
print(x[2])
print(x[-2])

[0 1 2 3 4 5 6 7 8 9]
2
8


In [2]:
# 二维
x.shape = (2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
print(x[1, 3])

8


In [4]:
print(x[1, -1])

9


In [5]:
print(x[0])

[0 1 2 3 4]


In [6]:
print(x[0,:])

[0 1 2 3 4]


In [7]:
print(x[0][2])

2


#### 1.2 切片和跨步
1. 基本切片语法是i:j:k,其中i是起始索引，j是停止索引，k是步骤

In [8]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[1:7:2])

[1 3 5]


In [9]:
print(x[-2:10])

[8 9]


In [10]:
print(x[-3:3:-1])

[7 6 5 4]


2. 假设n是要切片的维度中的元素数，如果没有给i,k >0时默认为0，k<0时默认为n-1.如果未给定j,则k>0时默认为n，k<0时默认为-n-1，如果未指定k，则默认为1，注意::与:相同，表示沿该轴的所有索引

In [11]:
print(x[5:])

[5 6 7 8 9]


3. 如果选择元组对象数小于N,则假设后继的任意维，例如

In [12]:
x  = np.array([[[1],[2],[3]],
                [[4],[5],[6]]])
print(x.shape)

(2, 3, 1)


In [13]:
print(x[1:2,2])

[[6]]


In [14]:
print(x[1:2,2,])

[[6]]


In [15]:
print(x[1:,2])

[[6]]


#### 2. 数组的索引
整数数组索引允许根据数组中的任意项的N维索引来选择它们，每个整数数组表示该维度中的多个索引，索引数组中允许出现负值，并且与处理间个索引或切片时一样

In [16]:
x = np.arange(10, 1, -1)

In [18]:
print(x)

[10  9  8  7  6  5  4  3  2]


In [19]:
print(x[np.array([3,3,1,8])])

[7 7 9 2]


In [20]:
print(x[np.array([3,3,-3,8])])

[7 7 4 2]


如果索引超出界限，则引发IndexError


In [22]:
x = np.array([[1,2],[3,4],[5,6]])
print(x.shape)

(3, 2)


In [23]:
print(np.array([1,-1]))

[ 1 -1]


In [24]:
print(x[1,-1])

4


In [25]:
x[np.array([-1,1])]

array([[5, 6],
       [3, 4]])

#### 布尔数组索引
当obj是布尔类型的数组对象(可能从比较运算返回)时，会发生这种高级索引
可能希望从非NaN的数组中选择所有的条目

In [27]:
x = np.array([[1.,2.], [np.nan, 3.], [np.nan, np.nan]])
print(~np.isnan(x))
print(x[~np.isnan(x)])

[[ True  True]
 [False  True]
 [False False]]
[1. 2. 3.]


#### 4. 缺省索引
不完全索引是从多维数组的第一个维度获取索引或切片的一种方便方法

In [32]:
a = np.arange(0, 100, 10)
print(a)
print(a.shape)
b = a[:5]
print(b)
c = a[a >= 50]
print(c)

[ 0 10 20 30 40 50 60 70 80 90]
(10,)
[ 0 10 20 30 40]
[50 60 70 80 90]


#### 5. 索引数组与切片组合

In [34]:
y = np.arange(35).reshape(5,7)
print(y)
print("=====================")
print(y[np.array([0,2,4]), 1:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 1  2]
 [15 16]
 [29 30]]
