#### 矩阵的四则运算

In [4]:
import numpy as np

a = np.random.randint(low=1, high=100, size=(3, 3))
b = np.random.randint(low=1, high=100, size=(3, 3))
print(f"a:\n{a}, type:{type(a)}")
print("a.shape() = ", a.shape)
print(f"b:\n{b}")

a:
[[59  4 30]
 [23 88 78]
 [40  7 53]], type:<class 'numpy.ndarray'>
a.shape() =  (3, 3)
b:
[[24 35 10]
 [29 23 25]
 [22 40 46]]


#### 向量相乘，得到内积

In [5]:
x=np.array([0,1,2,3,4]) #等价于 x=np.arange(0,5)
y=x[::-1]
print(x)
print(y)
print(np.dot(x,y))

[0 1 2 3 4]
[4 3 2 1 0]
10


#### 矩阵相乘，得到矩阵的积

In [7]:
x=np.arange(0,5)
print(x.shape)
# 0,10，是随机数的方位，size=(5,1),也就是5维矩阵，且每一维元素数为1个
y=np.random.randint(0,10,size=(5,1))
print(x)
print(y)
# 查看矩阵或者数组的维数
print("x.shape:"+str(x.shape))
print("y.shape"+str(y.shape))
print(np.dot(x,y))

(5,)
[0 1 2 3 4]
[[8]
 [4]
 [6]
 [5]
 [6]]
x.shape:(5,)
y.shape(5, 1)
[55]


In [8]:
x=np.arange(0,6).reshape(2,3)
y=np.random.randint(0,10,size=(3,2))
print(x)
print(y)
print("x.shape:"+str(x.shape))
print("y.shape"+str(y.shape))
print(np.dot(x,y))

[[0 1 2]
 [3 4 5]]
[[5 2]
 [1 6]
 [8 7]]
x.shape:(2, 3)
y.shape(3, 2)
[[17 20]
 [59 65]]


In [9]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

texts=["dog cat fish","dog cat cat","fish bird", 'bird'] # “dog cat fish” 为输入列表元素,假设代表一篇文章的所有字符串
cv = CountVectorizer()#创建词袋数据结构
cv_fit=cv.fit_transform(texts)

print(cv.get_feature_names())    #['bird', 'cat', 'dog', 'fish'] 列表形式呈现文章生成的词典，以字母顺序进行排列

print(cv.vocabulary_)              # {‘dog’:2,'cat':1,'fish':3,'bird':0} 字典形式呈现，key：词，value:在词袋列表中的index

print(cv_fit)
'''
  (0, 2)	1  #第0个列表元素"dog cat fish"，词典中索引为2的元素:‘dog’， 词频为1
  (0, 1)	1
  (0, 3)	1
  (1, 2)	1
  (1, 1)	2
  (2, 3)	1
  (2, 0)	1
  (3, 0)	1
  '''
print(cv_fit.toarray()) #.toarray() 是将结果转化为稀疏矩阵矩阵的表示方式；
'''
[[0 1 1 1]#"dog cat fish"
 [0 2 1 0]#"dog cat cat"
 [1 0 0 1]#"fish bird"
 [1 0 0 0]]#'bird'
'''

print(cv_fit.toarray().sum(axis=0))  #每个词在所有文档中的词频
#[2 3 2 2]#dog:2,cat:3,fish:3,bird:2
print(cv_fit.shape)#(4, 4)


tfidf = TfidfTransformer()
tfidf_fit = tfidf.fit_transform(cv_fit)
print(tfidf_fit)
'''
  (0, 3)	0.5773502691896257 #dog cat fish中dog对应的tfidf值
  (0, 2)	0.5773502691896257
  (0, 1)	0.5773502691896257
  (1, 2)	0.4472135954999579
  (1, 1)	0.8944271909999159
  (2, 3)	0.7071067811865475
  (2, 0)	0.7071067811865475
  (3, 0)	1.0
'''
print(tfidf_fit.toarray())
'''#对应的稀疏矩阵
[[0.         0.57735027 0.57735027 0.57735027]
 [0.         0.89442719 0.4472136  0.        ]
 [0.70710678 0.         0.         0.70710678]
 [1.         0.         0.         0.        ]]
'''

print(tfidf_fit.shape)#(4, 4)



AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'