## Lab1. Tensor Manipulation

In [2]:
# Import modules
import numpy as np
import torch

#### 1D Array witch NumPy

In [2]:
t = np.array([0.,1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
print(t)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [3]:
print(f"Rank of t:", t.ndim)
print(f"Shape of t:", t.shape)

Rank of t: 1
Shape of t: (11,)


In [ ]:
print('t[0],t[1],t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5], t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2],t[3:] = ', t[:2], t[3:]) # slicing

#### 2D Array with NumPy

In [4]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print(f"Rank of t:", t.ndim)
print(f"Shape of t:", t.shape)

Rank of t: 2
Shape of t: (4, 3)


#### Pytorch is like NumPy(but better)
###### 1D Array with PyTorch

In [6]:
t = torch.FloatTensor([0.,1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
print(t)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [7]:
print(t.dim()) # Rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:]) # slicing

1
torch.Size([11])
torch.Size([11])
tensor(0.) tensor(1.) tensor(10.)
tensor([2., 3., 4.]) tensor([4., 5., 6., 7., 8., 9.])
tensor([0., 1.]) tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


#### 2D Array with PyTorch

In [8]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim()) # Rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### Frequently Used Operations in PyTorch
##### Mul va Matmul 点乘和@乘

In [10]:
m1 = torch.tensor([[1,2], [3,4]])
m2 = torch.tensor([[1], [2]])
print("shape of matrix 1 is:", m1.shape)
print("shape of matrix 2 is:", m2.shape)
print(m1.matmul(m2))
print(m1.matmul(m2).size())
print(m1.mul(m2))
print(m1.mul(m2).size())

shape of matrix 1 is: torch.Size([2, 2])
shape of matrix 2 is: torch.Size([2, 1])
tensor([[ 5],
        [11]])
torch.Size([2, 1])
tensor([[1, 2],
        [6, 8]])
torch.Size([2, 2])


#### Brodcasting

In [11]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


#### mean

In [13]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [3]:
# can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as e:
    print(e)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


#### you can also use t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [6]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
