## Lab1. Tensor Manipulation

In [2]:
# Import modules
import numpy as np
import torch


#### 1D Array witch NumPy

In [2]:
t = np.array([0.,1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
print(t)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [3]:
print(f"Rank of t:", t.ndim)
print(f"Shape of t:", t.shape)

Rank of t: 1
Shape of t: (11,)


In [ ]:
print('t[0],t[1],t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5], t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2],t[3:] = ', t[:2], t[3:]) # slicing

#### 2D Array with NumPy

In [4]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print(f"Rank of t:", t.ndim)
print(f"Shape of t:", t.shape)

Rank of t: 2
Shape of t: (4, 3)


#### Pytorch is like NumPy(but better)
###### 1D Array with PyTorch

In [6]:
t = torch.FloatTensor([0.,1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
print(t)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [7]:
print(t.dim()) # Rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:]) # slicing

1
torch.Size([11])
torch.Size([11])
tensor(0.) tensor(1.) tensor(10.)
tensor([2., 3., 4.]) tensor([4., 5., 6., 7., 8., 9.])
tensor([0., 1.]) tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


#### 2D Array with PyTorch

In [8]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim()) # Rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### Frequently Used Operations in PyTorch
##### Mul va Matmul 点乘和@乘

In [10]:
m1 = torch.tensor([[1,2], [3,4]])
m2 = torch.tensor([[1], [2]])
print("shape of matrix 1 is:", m1.shape)
print("shape of matrix 2 is:", m2.shape)
print(m1.matmul(m2))
print(m1.matmul(m2).size())
print(m1.mul(m2))
print(m1.mul(m2).size())

shape of matrix 1 is: torch.Size([2, 2])
shape of matrix 2 is: torch.Size([2, 1])
tensor([[ 5],
        [11]])
torch.Size([2, 1])
tensor([[1, 2],
        [6, 8]])
torch.Size([2, 2])


#### Brodcasting

In [11]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


#### mean

In [13]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [3]:
# can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as e:
    print(e)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


#### you can also use t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [6]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### sum

In [3]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [6]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### Max and argmax

In [7]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.max()) # Return one value:max

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


The max operator returns 2 values when called with dimension specified, The first value is the maximum value, and the second value is the argmax: the index of the elemen with maximum value

In [8]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max:', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max: tensor([3., 4.])
Argmax: tensor([1, 1])


#### View

In [12]:
t = np.array([[[0,1,2],
              [3,4,5]],
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [13]:
print(ft.view(-1, 3))
print(ft.view(-1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [15]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### squeeze
- 去除数值为1的维度

In [16]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [17]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### unsqueeze

In [19]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)


torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [21]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [23]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### scatter(for one-hot encoding)

In [25]:
lt = torch.LongTensor([[0],[1],[2],[0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [26]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


#### casting

In [27]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [28]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [29]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [30]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#### concatenation

In [31]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### Stacking

In [32]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [35]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

#### Ones and Zeros Like

In [36]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [37]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### In-place Operation

In [38]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
