In [3]:
from __future__ import print_function
import torch
a = torch.ones(5)
print(a)
# 将Torch Tensor转换成Numpy array
b  = a.numpy()
print(b)
# 对其中一个做加法操作，另一个也随之被改变
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### 注意
- **所有在CPU上和Tensors，除了CharTensor，都可以转换为Numpy array并可以反向转换**

In [5]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### 关于Cuda Tensor:Tensors可以用.to()方法将其移动到任意设备上

In [6]:
x = torch.rand(1)
# 如果服务器上已经安装了GPU和CUDA
if torch.cuda.is_available():
    # 定义一个设备对象，这里指定成CUDA,即使用GPU
    device = torch.device("cuda")
    # 直接在GPU上创建一个Tensor
    y = torch.ones_like(x, device=device)
    # 将CPU上面的x张量移动到GPU上面
    x = x.to(device)
    # x和y都在GPU上面，才能支持加法运算
    z = x + y
    # 此处的张量z在GPU上面
    print(z)
    # 也可以将z移动到CPU上面，并同时指定张量元素的数据类型
    print(z.to("cpu", torch.double))

In [7]:
x

tensor([0.7576])

#### 小节总结
- 学习什么是Pytorch
    - pytorch是一个基于Numpy的科学计算包，作为Numpy的替代者，向用户提供使用CPU强大功能的能力
    - 做为一款深度学习的平台，向用户提供了最大的灵活性和速度
- 学习了pytorch的基本元素操作
    - 矩阵的初始化
        - torch.empty()
        - torch.rand(n,m)
        - torch.zeros(n,m, dtype=torch.long)
    - 其他操作
        - x.new_ones(n,m,dtype=torch.double)
        - torch.randn_like(x, dtype=torch.float)
        - x.size()
- 学习了pytorch的基本运算操作
    - 加法操作
        - x + y
        - torch.add(x,y)
        - torch.add(x, y, out=result)
        - y.add_(x)
    - 其它操作
        - x.view()
        - x.item()

- 学习了torch tensor和Numpy Array之间的相互转换
    - 将torch tensor转换成numpy array:
        - b = a.numpy()
    - 将numpy array转换成torch tensor:
        -  b = torch.from_numpy(a)
    - 注意所有在CPU上的tensor,除了CharTensor，都可以转换为Numpy Array并可以反向转换
- 学习了任意的Tensors可以用.to()方法来将其移动到任意设备上
    - x = x.to(device)