#### 什么是pytorch
- pytorch是一个基于Numpy的科学计算包，向它的使用都提供了两大功能
- 作为Numpy的替代者，向用户提供使用GPU强大功能的能力
- 做为一款深度学习的平台，向用户提供最大的灵活性和速度

#### pytorch的基本元素操作
- Tensors张量：张量的概念类似于Numpy中的ndarray数据的结构，最大的区别在于Tensor可以利用GPU的加速功能
- 我们使用pytorch的时候，常规步骤是先将torch引用进来

In [2]:
from __future__ import print_function
import torch

#### 创建矩阵的操作
- 创建一个没有初始化的矩阵

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### 创建一个有初始化的矩阵

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6491, 0.3415, 0.9360],
        [0.1550, 0.3730, 0.1595],
        [0.4179, 0.4133, 0.9248],
        [0.3110, 0.6352, 0.7822],
        [0.5407, 0.9972, 0.0092]])


- 对比有无初始化的矩阵：当声明一个未初始化的矩阵时，它本身不包含任何确切的值，当创建一个未初始化的矩阵时，分配给矩阵的内存中有什么数值就赋值给了这个矩阵，本质上是毫无意义的数据

#### 创建一个全零矩阵并可指定数据元素的类型为long

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### 直接通过数据创建张量

In [7]:
x = torch.tensor([2.5, 3.5])
print(x)

tensor([2.5000, 3.5000])


#### 通过已有的一个张量创建相同尺寸的新张量

In [8]:
# 利用new_ones方法得到一个张量
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# 利用randn_like方法得到相同张量尺寸的一个新张量，并且采用随机初始化来对其赋值
y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6352,  0.9007,  0.9983],
        [ 1.7751,  0.0601,  2.0170],
        [-1.2271, -0.8103,  0.6210],
        [-0.4695, -0.5939,  0.0025],
        [ 0.2436, -0.8803,  0.8707]])


#### 得到张量的尺寸

In [10]:
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([5, 3])


#### 注意：
- **torch.Size函数本质上返回的是一tuple，因此它支持一切元组的操作**

In [11]:
a, b = x.size()
print(a)
print(b)

5
3


#### pytorch基本运算操作
- 加法操作

In [13]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.6932, 0.9779, 0.8344],
        [0.2069, 0.5452, 0.3010],
        [0.9118, 0.8342, 0.3863],
        [0.4634, 0.0683, 0.1821],
        [0.1858, 0.1884, 0.6022]])
tensor([[1.6932, 1.9779, 1.8344],
        [1.2069, 1.5452, 1.3010],
        [1.9118, 1.8342, 1.3863],
        [1.4634, 1.0683, 1.1821],
        [1.1858, 1.1884, 1.6022]], dtype=torch.float64)


#### 第二种加法操作

In [15]:
print(torch.add(x, y))

tensor([[1.6932, 1.9779, 1.8344],
        [1.2069, 1.5452, 1.3010],
        [1.9118, 1.8342, 1.3863],
        [1.4634, 1.0683, 1.1821],
        [1.1858, 1.1884, 1.6022]], dtype=torch.float64)


#### 第三种加法方式

In [16]:
# 提前设定一个空的张量
result = torch.empty(5, 3)
# 将空的张量作为加法的结果存储张量
torch.add(x, y, out=result)
print(result)

tensor([[1.6932, 1.9779, 1.8344],
        [1.2069, 1.5452, 1.3010],
        [1.9118, 1.8342, 1.3863],
        [1.4634, 1.0683, 1.1821],
        [1.1858, 1.1884, 1.6022]])


#### 第四种方式：in-place(原地置换)

In [20]:
# 执行的功能是y = y + x
print(y)
y.add_(x)
print(y)

tensor([[2.6932, 2.9779, 2.8344],
        [2.2069, 2.5452, 2.3010],
        [2.9118, 2.8342, 2.3863],
        [2.4634, 2.0683, 2.1821],
        [2.1858, 2.1884, 2.6022]])
tensor([[3.6932, 3.9779, 3.8344],
        [3.2069, 3.5452, 3.3010],
        [3.9118, 3.8342, 3.3863],
        [3.4634, 3.0683, 3.1821],
        [3.1858, 3.1884, 3.6022]])


#### 注意
- **所有in-place的操作函数都有一个下划线的后缀**
- **比如x.copy_(y), x.add_(y)都会直接改变x的值**

#### 用类似于Numpy的方式对张量进行操作

In [24]:
print(x)
print(x[:,1]) # 第二列

tensor([[ 1.5686,  2.1318,  1.6644,  0.2305],
        [-1.0123,  0.0386, -0.2713,  2.3272],
        [ 2.2332, -0.9219, -1.4755, -0.9838],
        [ 0.0248,  1.3036, -0.5197, -1.4859]])
tensor([ 2.1318,  0.0386, -0.9219,  1.3036])


#### 改变张量的形状:torch.view()

In [25]:
x = torch.randn(4, 4)
# tensor.view()操作需要保证数据元素的总数量不变
y = x.view(16)
#  -1代表自动匹配个数
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.7934, -1.2125, -0.5185, -1.1373,  0.0491, -0.7663,  1.9066, -0.5302],
        [ 0.1579, -0.6867, -0.5759, -1.8587,  0.6831,  0.0361,  0.7800,  0.6267]])


#### 如果张量中只有一个元素，可以用.item()将值取出，作为一个python number

In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2171])
-0.21707990765571594


#### 关于Torch Tensor和Numpy array之间的相互转换
- **Torch Tensor和Numpy array共享底层的内存空间，因此改变其中一个的值，另一个也会随之被改变**


In [3]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


#### 将Torch Tensor转换为Numpy array

In [5]:
b  = a.numpy()
print(b)

[1. 1. 1. 1. 1.]
